### ISSUE TITLE
Google Now constantly crashing on s7 edge

### ISSUE THREAD

**Issue by mpiccoli2** [paphonb/PixelLauncherModV5#4]
Just pointing out that from version ~ 5.2.0 (i can't remember exactly what version i did have) till current version build 5.3_23, google now need to be restarted from Launcher's settings (off - on show google now) on my s7 edge 7.0 april 2018 security patch). 
Thank you for all your work, you are awesome!

**Comment by paphonb** [comment]
This problem is caused by Google App and I can't control its behaviors. Sorry.
