### ISSUE TITLE
Compatibility Navigation gesture xda 1.0.2

### ISSUE THREAD

**Issue by spippo71** [paphonb/PixelLauncherModV5#8]
Hi, I was wondering if compatibility with this function is possible.In practice, applying the "Navigation Gesture" service, xda app, this makes the navigation bar disappear.With our Launcher everything goes down, as normal as it is.Is it possible not to let everything down to make room for the white line for the gesture? Thank you

**Comment by spippo71** [comment]
the spacing of the gesture line is more regular in height but activating the service does not leave any space :-(

**Comment by spippo71** [comment]
![screenshot_20180527-145048](https://user-images.githubusercontent.com/25100846/40586131-6a422246-61bd-11e8-8719-66e4b973b5cd.png)
![screenshot_20180527-145058](https://user-images.githubusercontent.com/25100846/40586132-6a63e64c-61bd-11e8-9bf7-35ca41ca714e.png)

**Comment by paphonb** [comment]
Please read my comment again. From programming perspective, I have no idea if the XDA's app is enabled or not. And as of now, there's no way to figure that out unless they make some sort of an API for me to use.

**Comment by spippo71** [comment]
Ok sir, it was just a way to make you understand visually how it works. I understood very well that you need to understand how it works and what the app does Thank you

**Comment by paphonb** [comment]
No further reply so I guess that means no. Closing this.
